#!/usr/bin/env python
from pharmgkb import pipelines

import argparse
import fileinput
import sys

def main():
    parser = argparse.ArgumentParser(description="post-process a .csv file generated by scrapy, collapsing rows that would otherwise cause duplicate primary keys")
    parser.add_argument('--output', '-o', type=argparse.FileType('w'), default=sys.stdout)
    parser.add_argument('file')
    args = parser.parse_args()

    pipelines.collapse_by_key(args.file, args.output, separator=". ")

if __name__ == '__main__':
    main()
